"""Add cat area column

Revision ID: 223c621d4325
Revises: c798957f2d5b
Create Date: 2023-12-27 11:51:36.423355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223c621d4325'
down_revision = 'c798957f2d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
